### ISSUE TITLE
Nuget Error

### ISSUE THREAD

**Issue by ngchintamani** [Cryptolens/cryptolens-dotnet#54]
In VS 2019 while adding Cryptolens.Licensing it gives following error.

Error		An error occurred while retrieving package metadata for 'Cryptolens.Licensing.4.0.25' from source 'Package source'.
Failed to fetch results from V2 feed at 'https://www.nuget.org/FindPackagesById()?id='Cryptolens.Licensing'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 404 (Not Found).
Response status code does not indicate success: 404 (Not Found).

**Comment by artemlos** [comment]
Hi! This seems to be an issue. I saw had an error on their status page: https://status.nuget.org/. You can always use the binaries provided in this repo as an alternative.

@ngchintamani
